"""empty message

Revision ID: 1d3b7c5df2ac
Revises: 3f40a4ee79fb
Create Date: 2018-02-15 14:26:26.113530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d3b7c5df2ac'
down_revision = '3f40a4ee79fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('os_version', sa.String(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registrant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('command', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('current_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registrant_id', sa.Integer(), nullable=True),
    sa.Column('last_execution_id', sa.Integer(), nullable=True),
    sa.Column('last_successful_execution_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['last_execution_id'], ['execution_record.id'], ),
    sa.ForeignKeyConstraint(['last_successful_execution_id'], ['execution_record.id'], ),
    sa.ForeignKeyConstraint(['registrant_id'], ['registrant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('failure_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registrant_id', sa.Integer(), nullable=True),
    sa.Column('execution_id', sa.Integer(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['execution_record.id'], ),
    sa.ForeignKeyConstraint(['registrant_id'], ['registrant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('failure_record')
    op.drop_table('current_record')
    op.drop_table('registrant')
    op.drop_table('execution_record')
    # ### end Alembic commands ###
