"""empty message

Revision ID: 8f9d1ed0332a
Revises: 3f40a4ee79fb
Create Date: 2018-02-05 16:14:31.565203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f9d1ed0332a'
down_revision = '3f40a4ee79fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('os_version', sa.String(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('current_record',
    sa.Column('registrant_id', sa.Integer(), nullable=False),
    sa.Column('last_execution_id', sa.Integer(), nullable=True),
    sa.Column('last_successful_execution_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['last_execution_id'], ['execution_record.id'], ),
    sa.ForeignKeyConstraint(['last_successful_execution_id'], ['execution_record.id'], ),
    sa.ForeignKeyConstraint(['registrant_id'], ['program.id'], ),
    sa.PrimaryKeyConstraint('registrant_id')
    )
    op.create_table('failure_record',
    sa.Column('registrant_id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['execution_record.id'], ),
    sa.ForeignKeyConstraint(['registrant_id'], ['program.id'], ),
    sa.PrimaryKeyConstraint('registrant_id', 'execution_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('failure_record')
    op.drop_table('current_record')
    op.drop_table('execution_record')
    # ### end Alembic commands ###
